# Generated by Django 4.2.14 on 2025-11-05 14:32

from django.db import migrations, models
import django.db.models.deletion


def set_exchange(apps, schema_editor):
    Registration = apps.get_model("registration", "Registration")
    Exchange = apps.get_model("registration", "Exchange")
    for registration in Registration.objects.all().iterator():
        if registration.session:
            exchange = registration.session.exchange
        else:
            exchange = Exchange.objects.get(begin=registration.date_time.year)
        registration.exchange = exchange
        registration.save()


def unset_exchange(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="exchange",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.exchange",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_exchange, unset_exchange),
        migrations.AlterField(
            model_name='registration',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.exchange'),
        ),
    ]
