# Generated by Django 4.2.14 on 2025-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='reason',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
