# Generated by Django 4.2.14 on 2025-11-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registration_notes_registration_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reason',
            field=models.CharField(blank=True),
        ),
    ]
