# Generated by Django 4.2.14 on 2026-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_registration_notes_alter_registration_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
